"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-18 20:22:10.415753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint("subject IN ('Biology', 'Physics', 'Chemistry', 'Mathematics')", name='ck_exams_subject'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sa.String(length=8), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('generation_batch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("subject IN ('Biology', 'Physics', 'Chemistry', 'Mathematics')", name='ck_questions_subject'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('kcet_student_id', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('student', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('kcet_student_id', name='uq_users_kcet_student_id')
    )
    op.create_table('exam_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('set_label', sa.String(length=1), nullable=False),
    sa.CheckConstraint("set_label IN ('A', 'B', 'C', 'D')", name='ck_exam_sets_label'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'set_label', name='uq_exam_sets_exam_label')
    )
    op.create_table('leaderboard_scores',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('composite_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('average_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('std_dev', sa.Float(), server_default='0', nullable=False),
    sa.Column('is_eligible', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('recomputed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('exam_set_questions',
    sa.Column('exam_set_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_set_id'], ['exam_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_set_id', 'question_id', name='pk_exam_set_questions')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exam_set_id', sa.Uuid(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=False),
    sa.Column('topic_breakdown', sa.JSON(), nullable=False),
    sa.Column('time_taken_sec', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'failed')", name='ck_submissions_status'),
    sa.ForeignKeyConstraint(['exam_set_id'], ['exam_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('exam_set_questions')
    op.drop_table('leaderboard_scores')
    op.drop_table('exam_sets')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_table('questions')
    op.drop_table('exams')
    # ### end Alembic commands ###
